
@BASE_URL = http://localhost:3000


### Get API Root Info
GET {{BASE_URL}}/


### Health Check
GET {{BASE_URL}}/health


### Register a new user
POST {{BASE_URL}}/api/auth/register
Content-Type: application/json

{
  "name": "Jonson Carter",       
  "email": "kinih12939@fengnu.com",    
  "password": "12345678",
  "confirmPassword": "12345678" 
}


### Login user
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
  "email": "kinih12939@fengnu.com",     
  "password": "12345678"         
}


### Logout user
POST {{BASE_URL}}/api/auth/logout


### Create funeral plan
POST {{BASE_URL}}/api/plans
Content-Type: application/json

{
  "location": "Lagos",
  "budgetEstimate": 1000000,
  "ritualPreference": {
    "ceremonyType": "Muslim",
    "durationDays": 3,
    "preferredLocation": "Mosque",
    "preferredTime": "Afternoon",
    "musicPreference": "Islamic",
    "foodPreference": "Halal",
    "guestCount": 100,
    "specialRequests": "None"
  }
}


### Get funeral plan
GET {{BASE_URL}}/api/plans/me
Content-Type: application/json


### Update funeral plan
PATCH {{BASE_URL}}/api/plans/e7834c55-9a47-425b-b00f-142fa66bc9fc
Content-Type: application/json

{
  "status": "finalized"
}


### Add nominee
POST {{BASE_URL}}/api/plans/e7834c55-9a47-425b-b00f-142fa66bc9fb/nominees
Content-Type: application/json

{
  "name": "Alex",       
  "email": "alex@duck.com",    
  "phone": "1234567808",
  "relation": "Brother" 
}


### Delete nominee
DELETE {{BASE_URL}}/api/plans/e7834c55-9a47-425b-b00f-142fa66bc9fc/nominees/37f4b82f-91fe-4a7e-8225-9ca6b4777db6


### Get plan by nominee token
GET {{BASE_URL}}/api/nominee/plan/050e87b8-0dd8-4f2a-87c9-10df39747987


### Create Business
POST {{BASE_URL}}/api/providers/profile
Content-Type: application/json

{
  "businessName": "Peaceful Rest",
  "type": "funeral_agency",
  "city": "New York",
  "phone": "123-456-7890"
}


### Get provider profile
GET {{BASE_URL}}/api/providers/profile


### Get providers
GET {{BASE_URL}}/api/providers